alias dc='setdir && docker-compose'
alias dcr='dc run'
alias dcu='dc up'
alias dcrm='dc run --rm'
alias dcx='dc exec'
alias php='dc run --rm php'
alias php_debug='dc run --rm php_debug'
alias artisan='php php artisan'
alias composer='php composer'
alias npm='dc run --rm npm'
alias node='dc run --rm node'
alias serve='dc up server'
alias reserve='dc up --build server'
alias fresh_seed='artisan migrate:fresh --seed'
alias pap='artisan passport:client --password'
alias fresh='fresh_seed && artisan passport:install && pap'
alias pu='php ./vendor/bin/phpunit'
alias pud='php_debug ./vendor/bin/phpunit'
alias puf='php ./vendor/bin/phpunit --filter'
alias pufd='php_debug ./vendor/bin/phpunit --filter'
alias pug='php ./vendor/bin/phpunit --group'
alias puc='php ./vendor/bin/phpunit --list-tests | wc -l'
alias puwchtml='php_debug -e XDEBUG_MODE=coverage ./vendor/bin/phpunit'
alias phpfixer='php ./vendor/bin/php-cs-fixer fix'
alias psalm='php ./vendor/bin/psalm --config=psalm.dist.xml'
alias setdir='$HOME/backend/set_work_dir.sh'
