name: "docusaurus"
services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/docusaurus
    environment:
      - NODE_ENV=development
  node: &node
    image: node:lts
    volumes:
      - .:/opt/docusaurus
    working_dir: /opt/docusaurus
  npm:
    <<: *node
    entrypoint: [ "npm" ]
